version: '3.8'
services:
  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - bridge
    environment:
      DATABASE_URI: mongodb+srv://root:82384580vV!@judit.mswln4j.mongodb.net/?retryWrites=true&w=majority&appName=judit
      APIKEY: 7fae0caf-060a-444c-a8ba-9d7966463700

networks:
  bridge:
    driver: bridge

volumes:
  mongodb_data_container:
