version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/teste
      APIKEY: "7fae0caf-060a-444c-a8ba-9d7966463700"
    volumes:
      - .:/app
    networks:
      - backend

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: teste
    networks:
      - backend

networks:
  backend:
    driver: bridge
